spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: patient-service
          uri: http://patient-service:8082
          predicates:
            - Path=/patients/**
        - id: file-service
          uri: http://file-service:8083
          predicates:
            - Path=/files/**
        - id: prescription-service
          uri: http://prescription-service:8084
          predicates:
            - Path=/prescriptions/**
        - id: notification-service
          uri: http://notification-service:8085
          predicates:
            - Path=/notifications/**
        - id: plan-service
          uri: http://plan-service:8086
          predicates:
            - Path=/plans/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

auth:
  jwt:
    secret: ${JWT_SECRET:my-secret-key}
